name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.SECRET_PAT_GITHUB}}
      -
        name: ACR
        uses: azure/docker-login@v1
        with:
          login-server: vvmmxpdfservicecr.azurecr.io
          username: ${{ secrets.VVM_MX_CR_SECRET_NAME }}
          password: ${{ secrets.VVM_MX_CR_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vvmmxpdfservicecr.azurecr.io/vvm-ms-pdf:1.${{ steps.buildnumber.outputs.build_number }} , vvmmxpdfservicecr.azurecr.io/vvm-ms-pdf:latest
